In [9]:
from sklearn.svm import SVC
import numpy as np
X = np.array([[42], [46], [52], [63]])
y = np.array([1, 1, 0, 0])
clf = SVC(kernel="linear",)
clf.fit(X, y)

SVC(kernel='linear')

In [25]:
clf.predict(np.array([[48.99999999999999]]))

array([1])

In [12]:
clf.class_weight_

array([1., 1.])

In [27]:
clf.coef_[0][0]

-0.3333333333333357

In [14]:
clf.shape_fit_ 

(4, 1)

In [28]:
clf.intercept_[0]/

16.333333333333456

In [21]:
-(1/3)*52+(16+1/3)

-1.0

In [22]:
(16+1/3)/(1/3)

49.0

In [30]:
-clf.intercept_[0]/clf.coef_[0][0]

49.00000000000002

In [35]:
X.reshape(1,-1).reshape(-1,1)

array([[42],
       [46],
       [52],
       [63]])

In [32]:
X.shape

(4, 1)

In [39]:
clf.score(X,y)

1.0