In [1]:
# 导入波士顿房价数据
from sklearn.datasets import load_boston
# 导入线性模型工具包
from sklearn import linear_model
# 分离训练集和测试集的工具包
from sklearn.model_selection import train_test_split

from sklearn.decomposition import PCA

In [2]:
# 下载波士顿房屋数据
Data = load_boston()
# 获取数据标签(房价)
y = Data.target
# 获取数据特征
X = Data.data

In [3]:
pca = PCA(n_components=3)
X = pca.fit_transform(X)

print(pca.explained_variance_ratio_)

print(pca.singular_values_)

[0.80582318 0.16305197 0.02134861]
[3949.60823205 1776.63071036  642.86374839]


In [4]:
# 划分训练数据和测试数据
X_train, X_test, y_train, y_test = train_test_split(
                                   X, y, test_size=0.1, random_state=22)
# 训练模型
reg = linear_model.LinearRegression()
reg.fit(X,y)

LinearRegression()

In [5]:
# 查看权重W
reg.coef_

array([-0.02548309, -0.00875964,  0.06811357])

In [6]:
# 查看偏置项b
reg.intercept_

22.532806324110663

In [7]:
# 查看模型得分
print("训练集得分:  %.2f" % reg.score(X_train,y_train))
print("测试集得分:  %.2f" % reg.score(X_test,y_test))

训练集得分:  0.28
测试集得分:  0.32


In [8]:
reg.score(X,y)

0.2877035731165076

In [10]:
from sklearn.datasets import load_boston
#样本数据
boston=load_boston()
x=boston.data
y=boston.target
#样本个数及特征数
#print(x.shape)
#特征标签名字
#print(boston.feature_names)
#把数据分为训练数据集和测试数据集
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)
import time
from sklearn.linear_model import LinearRegression
model=LinearRegression()
start=time.clock()
model.fit(x_train,y_train)
train_score=model.score(x_train,y_train)
cv_score=model.score(x_test,y_test)
print('elaspe:{0:.6f};train_score:{1:0.6f};cv_score:{2:.6}'.format(time.clock()-start,train_score,cv_score))
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
def polynomial_model(degree=1):
    polynomial_features=PolynomialFeatures(degree=degree,include_bias=False)
    linear_regression=LinearRegression(normalize=True)
    pipeline=Pipeline([("polynomial_features",polynomial_features),("linear_regression",linear_regression)])
    return pipeline
model=polynomial_model(degree=2)
start=time.clock()
model.fit(x_train,y_train)
train_score=model.score(x_train,y_train)
cv_score=model.score(x_test,y_test)
#print('elaspe:{0:.6f};train_score:{1:0.6f};cv_score:{2:.6}'.format(time.clock()-start,train_score,cv_score))
#画出特征学习曲线
from sklearn.model_selection import learning_curve
from sklearn.model_selection import ShuffleSplit
import numpy as np
import matplotlib.pyplot as plt
def plot_learning_curve(plt,estimator,title,X,y,ylim=None,cv=None):
    cv = ShuffleSplit(n_splits=10,test_size=0.2,random_state=0)
    plt.figure(figsize=(16,4),dpi=144)
    title='Learning Curves(degree={0})'
    degrees=[1,2,3]
    start=time.clock(0)
    plt.figure(figsize=(16,4),dpi=144)
    for i in range(len(degrees)):
        plt.subplot(1,3,i+1)
        plot_learning_curve(plt,polynomial_model(degrees[i]),
                            title.format(degrees[i]),x,y,ylim=(0.01,1.01),cv=cv)
print('elaspe:{0:.6f}'.format(time.clock()-start))
print('elaspe:{0:.6f};train_score:{1:0.6f};cv_score:{2:.6}'.format(time.clock()-start,train_score,cv_score))

elaspe:0.001610;train_score:0.723941;cv_score:0.795262
elaspe:0.005398
elaspe:0.005593;train_score:0.930547;cv_score:0.860049
